apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: cass-operator
spec:
  clusterName: test-cluster
  size: 3
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      cdc:
        enabled: true
        pulsarServiceUrl: pulsar://pulsar-proxy.default.svc.cluster.local:6650
        topicPrefix: persistent://public/default/events-cdc-
        cdcWorkingDir: /var/lib/cassandra/cdc
  serverVersion: "4.0.1"
  serverType: "cassandra"
